---
title: Search tool for possible undervalued Stocks with DCF and P/B and subsequent
  Stock evaluation
author: "Justin König"
date: "20.08.2022"
output:
  html_document:
    code_folding: show
    theme: yeti
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

# clean environment

rm(list=ls())
cat("\014")

# sets working directory to path in which the file is stored

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# loads functions

source("funcs/basics_data.R")
source("funcs/basics_assignement.R")
source("funcs/DCF_data_scraper.R")
source("funcs/DCF_calculation.R")
source("funcs/DCF_scraper_and_calculation_apply.R")
source("funcs/bookv_data.R")
source("funcs/calenderization.R")
source("funcs/DCF_data_scraper_v2.R")
source("funcs/DCF_calculation_v2.R")
source("funcs/calenderization.R")
source("funcs/Imp_Share_Price_calculation.R")
source("funcs/WACC_calculation.R")
```

```{r packages, include = FALSE}
# loads packages
library(tidyverse)
# library(ggplot2)
library(tidyr)
library(dplyr)
# library(lubridate)
# library(data.table)
# library(broom)
# library(XML)
# library(xml2)
library(rvest)
# library(httr)
library(quantmod)
library(tidyquant)
library(ggrepel)
library(DiagrammeR)
library(reshape2)
library(gt)
library(glue)
library(gridExtra)
```

## Motivation
Das wird mein Dokument


```{r Stocks}

# the chosen tickers of the Stocks are assigned with a vector to the variable 
# Ticker

# Ticker <-c("EOAN.DE", "GS", "MSFT", "AAPL", "BAC", "CRM", "NVDA", "NKE", "MS")

Ticker <- "NKE"

# creates a data frame out of the Tickers

Stocks <- data.frame(Ticker)

# variable Ticker is not longer needed, gets removed

rm(Ticker)

# uses the function basics_assignment on the data frame Stocks creating a list
# and then only uses the part of the list which is further needed

Stocks <- basics_assignement(Stocks)
Stocks <- Stocks$list
```
$$uFCF= \sum_{i=1}^n X_i$$
```{r Scraper and Calculation on List, results='hide'}
  toassaign_df <- Stocks
  x<-1
  DCF_ISP <-"DCF_ISP"
  DCF_ISP <- data.frame(DCF_ISP)
  PB <- "P/B"
  PB <- data.frame(PB)
  toassaign_df<- bind_cols(toassaign_df, DCF_ISP)
  toassaign_df<- bind_cols(toassaign_df, PB)
  
  while (x<=nrow(toassaign_df)) {
    company <- toassaign_df[paste(x),1]
    print(paste("checking Sector", x, "of",nrow(toassaign_df), "of", company))
    ticker <- toassaign_df[paste(x),2]
    check_for_fin <- isTRUE(toassaign_df[paste(x),3]=="Banks—Diversified" || toassaign_df[paste(x),3]=="Capital Markets" )
    if(check_for_fin=="FALSE"){
      print(paste("applying DCF scraper to", company))
      scraped_DCF_data <- lapply(toassaign_df$Ticker[as.numeric(paste(x))],DCF_data_scraper)
      print(paste("calculating fair value of", company))
      #required rate of return
      DCF_calc_data <- DCF_calculation()
      WACC_data <- WACC_calculation()
      ISP_data <- Imp_Share_Price_calculation()
      ISP <- ISP_data$ISP
      toassaign_df[paste(x),7] <- ISP
      print(paste("applying book value scraper to", company))
      toassaign_df[paste(x),8] <- bookv_data(ticker)
    }
    else {
      print(paste("applying book value scraper to", company))
      toassaign_df[paste(x),7] <- "NA"
      toassaign_df[paste(x),8] <- bookv_data(ticker)
    }
    x<-x+1
  }
toassaign_df$PB <- as.numeric(toassaign_df$PB)
toassaign_df$DCF_ISP <- as.numeric(toassaign_df$DCF_ISP)  
toassaign_df$Price <- as.numeric(toassaign_df$Price)
toassaign_df$PE <- as.numeric(toassaign_df$PE)
Stocks <- toassaign_df
```

```{r KA}
 # takes all Companys of the Dataframe with a lower Price then its fair value
 # and creates a new Dataframe out of it 

picks_DCF_ISP <- Stocks[Stocks$Price < Stocks$DCF_ISP,]

# removes all rows with NAs in it

picks_DCF_ISP <- picks_DCF_ISP %>% drop_na()

p_under_DCF_ISP <- (1-round(picks_DCF_ISP$Price/picks_DCF_ISP$DCF_ISP, 2))*100

p_under_DCF_ISP <- data.frame(p_under_DCF_ISP)

picks_DCF_ISP<- bind_cols(picks_DCF_ISP,p_under_DCF_ISP)

picks_DCF_ISP <- picks_DCF_ISP %>%
  arrange(desc(p_under_DCF_ISP))
  
picks_DCF_ISP <- slice(picks_DCF_ISP,1:2)

# takes all companys with a PB between 0 and 1.1 

picks_fin <- Stocks %>% filter(
  Industry == "Banks—Diversified" | Industry == "Capital Markets")
picks_fin <- picks_fin[picks_fin$PB < 1.5,]
picks_fin <- picks_fin[picks_fin$PB > 0,]
picks_fin <- picks_fin %>%
  arrange(PB)
picks_fin <- slice(picks_fin,1:2)

picks <- data.frame(picks_DCF_ISP)
picks <- bind_rows(picks, picks_fin)
picks <- slice(picks, )
droping <- "p_under_DCF_ISP"

picks <- picks[ , !(names(picks) %in% droping)]


# picks <- picks %>% distinct()

rownames(picks)<- c(1:nrow(picks))

picks <- picks %>% 
    rename(
      "P/E" = PE,
      "Implied share value" = DCF_ISP,
      "P/B" = PB
    )


```

```{r Flow Chart}
grViz("digraph flowchart {
      # node definitions with substituted label text
      node [fontname = Helvetica, shape = rectangle]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
      tab8 [label = '@@8']
      tab9 [label = '@@9']
     
      # edge definitions with the node IDs
      tab1 -> tab2 -> tab4 -> tab5 -> tab6 -> tab7
      tab1 -> tab3 -> tab8 -> tab9 -> tab6
    
    
      }

      [1]: 'Stocks'
      [2]: 'Non Financial Stocks'
      [3]: 'P/B between 0 and 1.5'
      [4]: 'Price lower as DCF implied share price'
      [5]: 'Top 2 highest ISP diff to Price'
      [6]: 'Picks to watch'
      [7]: 'Deeper analysis'
      [8]: 'Financial Stocks'
      [9]: 'Top 2 lowest P/B'
     
      
      ")
```


```{r Stock chart comperisisson}

# the chosen tickers of the Stocks are assigned with a vector to the variable 
# Ticker

ticker <- picks$Ticker

# counts 5 years into the past and sets it as start date for the plots
  
start_date <- ymd(format(Sys.Date())) - years(5)

prices <- tq_get(ticker,
                 from = start_date,
                 to = format(Sys.Date()),
                 get = "stock.prices")

prices <- prices %>% 
    rename(
      ticker = symbol,
    )

mean <- prices %>% group_by(ticker)%>%summarise(mean_val=mean(adjusted))
curr <- picks %>% arrange(Ticker)
curr <- curr$Currency
curr <- data.frame(curr)

mean <- bind_cols(mean, curr)

print(plot <- prices %>%
          ggplot(aes(x = date, y = adjusted, color = ticker)) +
          geom_line()+
          geom_hline(data = mean, aes(yintercept = mean_val, color = ticker))+
          facet_wrap(~ticker,scales = 'free_y')+
          theme_classic()+
          labs(x = 'Year',
           y = "Adjusted Price",
           title = "Stocks to watch") +
           scale_x_date(date_breaks = "year",
               date_labels = "%y")+
          geom_text(data = mean, aes(x = prices$date[250], y = mean_val, label = paste("avg.", round(mean_val,2), curr), vjust = -0.3), show.legend = F))
          
```

```{r Cash Flow Table}

ticker <- "NKE"
Ticker <- data.frame(ticker)


Stock <- basics_assignement(Ticker)
scraped_DCF_data <- lapply(ticker, DCF_data_scraper)
DCF_calc_data <- DCF_calculation()
WACC_data <- WACC_calculation()

attach(DCF_calc_data$calended_data)

# all Prices in Millions $ 

DCF_data_CYE <- data.frame(DCF_calc_data$calended_data[2:9])
DCF_data_CYE <- round(DCF_data_CYE[1:8]/1000000)
p_growth_Rev <- c("-", (TotalRevenue[2:9]/TotalRevenue[1:8]-1))
DCF_data_CYE <- add_column(DCF_data_CYE, p_growth_Rev = p_growth_Rev, .after = "TotalRevenue")
Operating_Margin <- EBIT[1:9]/TotalRevenue[1:9]
DCF_data_CYE <- add_column(DCF_data_CYE, Operating_Margin = Operating_Margin, .after = "EBIT")
p_of_EBIT <- IncTaxEx[1:9]/EBIT[1:9]
DCF_data_CYE <- add_column(DCF_data_CYE, p_of_EBIT = p_of_EBIT, .after = "IncTaxEx")
DandA_p_of_Rev <- DandA[1:9]/TotalRevenue[1:9]
DCF_data_CYE <- add_column(DCF_data_CYE, DandA_p_of_Rev = DandA_p_of_Rev, .after = "DandA")
CapEx_p_of_Rev <- CAPEX[1:9]/TotalRevenue[1:9]
DCF_data_CYE <- add_column(DCF_data_CYE, CapEx_p_of_Rev = CapEx_p_of_Rev, .after = "CAPEX")
cNWC_p_of_Rev <- cNWC[1:9]/TotalRevenue[1:9]
DCF_data_CYE <- add_column(DCF_data_CYE, cNWC_p_of_Rev = cNWC_p_of_Rev, .after = "cNWC")
p_growth_FCF <- c("-", (FCF[2:9]/FCF[1:8]-1))
DCF_data_CYE <- add_column(DCF_data_CYE, p_growth_FCF = p_growth_FCF, .after = "FCF")
pres_val_of_FCF <- c(rep(NA,4),round((FCF[5:9]/(1+WACC_data$T0_cal$RRR)^as.numeric(DiscountYear[5:9])/1000000)))
pres_val_of_FCF <- data.frame(pres_val_of_FCF)
DCF_data_CYE <- bind_cols(DCF_data_CYE,pres_val_of_FCF)

detach(DCF_calc_data$calended_data)
DCF_data_CYE <- DCF_data_CYE[3:9,]
DCF_data_CYE$p_growth_Rev <- as.numeric(DCF_data_CYE$p_growth_Rev)
DCF_data_CYE$p_growth_FCF <- as.numeric(DCF_data_CYE$p_growth_FCF)
DCF_data_CYE <- t(DCF_data_CYE)

Year <- DCF_calc_data$calended_data$Year[3:4]
Year <- c(Year, paste0(Year[2]+1, "E"), paste0(Year[2]+2, "E"), paste0(Year[2]+3, "E"), paste0(Year[2]+4, "E"), paste0(Year[2]+5, "E"))
colnames(DCF_data_CYE) <- Year

Year <- c("Revenue","growth y-o-y", "EBIT", "Operating margin", 
                             "Taxes","% of EBIT", "D&A", "% of revenue", "CapEx",
                             "% of revenue", "Change in NWC", "% of revenue",
                             "EBIAT", "uFCF", "growth y-o-y",  "Present value of FCF" )

DCF_data_CYE <- as_tibble(DCF_data_CYE)

DCF_data_CYE <- DCF_data_CYE %>% add_column(Year, .before = "2021")

DCF_table_CYE <- gt(DCF_data_CYE)

DCF_table_CYE <- 
  DCF_table_CYE %>%
  tab_header(
    title = glue("{Stock$list$Company} Discounted Cash Flow"),
    subtitle = glue("{Stock$list$Currency} in millions")
  ) %>%
  fmt_percent(
    columns = c(2:8),
    rows = c(2,4,6,8,10,12,15),
    decimals = 1
  ) %>%
    fmt_currency(
    columns = c(2:8),
    rows = c(1,3,5,7,9,11,13,14,16),
    currency = "USD",
    decimals = 0
    ) %>% 
  tab_style(
    style = list(
      cell_fill(color = "deepskyblue2")
    ),
    locations = cells_body(
      columns = c(2:8),
      rows = 14)
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = "deepskyblue2")
    ),
    locations = cells_body(
      columns = c(4:8), # not needed if coloring all columns
      rows = 16)
)


DCF_table_CYE
```

```{r Price per Share Table}
ISP_data <- Imp_Share_Price_calculation()

attach(ISP_data)
attach(scraped_DCF_data[[1]]$T0Data)
attach(Stock$list)

Discount <- 1-as.numeric(Price)/ISP

Tot_PV_p_FCF <- sum(as.numeric(UnlevFCF))
PPS_data <- bind_cols(Tot_PV_p_FCF,PTermValue,EntpriVal,EquValue,
                      floatshares, ISP[1], Price, Discount )

detach(ISP_data)
detach(scraped_DCF_data[[1]]$T0Data)
detach(Stock$list)
PPS_data$...7 <- as.numeric(PPS_data[7])

PPS_data[1:5] <- round(PPS_data[1:5]/1000000)
PPS_data <- t(PPS_data)
curYear <- format(Sys.Date())
curYear <- year(curYear)

colnames(PPS_data) <- curYear
Year <- c("Total PV of proj. FCF", "PV Terminal VAlue", "Enterprise Value",
          "Equity Value", "Shares outstanding", "Implied Share Price", 
          "Current Share Price", "Discount")

PPS_data <- as_tibble(PPS_data)
PPS_data <- PPS_data %>% add_column(Year, .before = "2022")
PPS_table <- gt(PPS_data)

PPS_table <- 
  PPS_table %>%
  tab_header(
    title = "Price per Share",
    subtitle = glue("Numbers in millions, unless otherwise stated")
  ) %>%
  fmt_percent(
    columns = `2022`,
    rows = 8,
    decimals = 1
  ) %>%
    fmt_currency(
    columns = `2022`,
    rows = c(1,2,3,4,6,7),
    currency = "USD",
    decimals = 0
    )  %>%
  tab_footnote(
    footnote = "not in millions",
    locations = cells_body(
    columns = 1, 
    rows = 6:8)
  ) %>%
tab_style(
    style = list(
      cell_fill(color = "deepskyblue2")
    ),
    locations = cells_body(
      columns = c(2),
      rows = 6)
)
rm(Year)
PPS_table

```

```{r Revenue and EBIT Bar Graph}
bar_graph_data <- bind_cols(DCF_calc_data$calended_data[1],
                            round(DCF_calc_data$calended_data[2:3]/1000000))
colnames(bar_graph_data) <- c("Year","Revenue","EBIT")



mel_bar_data <- reshape2::melt(bar_graph_data, id.var = "Year")

bar_graph_rev_EBIT  <- ggplot(mel_bar_data, aes(x=Year, y=value, fill = variable)) + 
  geom_bar(stat = "identity", position = "dodge")+
  theme_classic()+
  theme(legend.position="top",
        legend.title=element_blank())+
  ylab("USD in Millions")+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  scale_x_continuous("Year", labels = as.character(bar_graph_data$Year), breaks = bar_graph_data$Year)
bar_graph_rev_EBIT <- bar_graph_rev_EBIT + ggtitle("Revenue and EBIT development")

plot(bar_graph_rev_EBIT)

```

```{r Nike, S$P500 and Competitors}

ticker <- c("NKE", "^GSPC","ADDYY", "UA" )

# counts 5 years into the past and sets it as start date for the plots
  
start_date <- ymd(format(Sys.Date())) - years(5)

year1 <- start_date + years(1) + days(2)
year2 <- start_date + years(2) + days(1)
year3 <- start_date + years(3)
year4 <- start_date + years(4) 
lastdate <- ymd(format(Sys.Date())) - days(1)

prices <- tq_get(ticker,
                 from = start_date,
                 to = format(Sys.Date()),
                 get = "stock.prices")

prices <- prices %>% 
    rename(
      ticker = symbol,
    )

return_rate_d <- prices[prices$date == start_date, ]
return_rate_d <- bind_rows(return_rate_d, prices[prices$date == year1, ], 
               prices[prices$date == year2, ], 
               prices[prices$date == year3, ],
               prices[prices$date == year4, ],
               prices[prices$date == lastdate, ])

return_rate_NKE <- return_rate_d[return_rate_d$ticker == "NKE", ]
return_rate_NKE <- (return_rate_NKE$adjusted[2:6]-return_rate_NKE$adjusted[1:5])/return_rate_NKE$adjusted[1:5]



return_rate_SP500 <- return_rate_d[return_rate_d$ticker == "^GSPC", ]
return_rate_SP500 <- (return_rate_SP500$adjusted[2:6]-return_rate_SP500$adjusted[1:5])/return_rate_SP500$adjusted[1:5]


return_rate_adi <- return_rate_d[return_rate_d$ticker == "ADDYY", ]
return_rate_adi <- (return_rate_adi$adjusted[2:6]-return_rate_adi$adjusted[1:5])/return_rate_adi$adjusted[1:5]


return_rate_ua <- return_rate_d[return_rate_d$ticker == "UA", ]
return_rate_ua <- (return_rate_ua$adjusted[2:6]-return_rate_ua$adjusted[1:5])/return_rate_ua$adjusted[1:5]


x <- 1000

m_return_NKE <- c(x, x*return_rate_NKE[1]+x, (x*return_rate_NKE[1]+x)*return_rate_NKE[2]+(x*return_rate_NKE[1]+x))
m_return_NKE <- c(m_return_NKE, m_return_NKE[3]*return_rate_NKE[3]+m_return_NKE[3])
m_return_NKE <- c(m_return_NKE, m_return_NKE[4]*return_rate_NKE[4]+m_return_NKE[4])
m_return_NKE <- c(m_return_NKE, m_return_NKE[5]*return_rate_NKE[5]+m_return_NKE[5])

m_return_SP500 <- c(x, x*return_rate_SP500[1]+x, (x*return_rate_SP500[1]+x)*return_rate_SP500[2]+(x*return_rate_SP500[1]+x))
m_return_SP500 <- c(m_return_SP500, m_return_SP500[3]*return_rate_SP500[3]+m_return_SP500[3])
m_return_SP500 <- c(m_return_SP500, m_return_SP500[4]*return_rate_SP500[4]+m_return_SP500[4])
m_return_SP500 <- c(m_return_SP500, m_return_SP500[5]*return_rate_SP500[5]+m_return_SP500[5])

m_return_adi <- c(x, x*return_rate_adi[1]+x, (x*return_rate_adi[1]+x)*return_rate_adi[2]+(x*return_rate_adi[1]+x))
m_return_adi <- c(m_return_adi, m_return_adi[3]*return_rate_adi[3]+m_return_adi[3])
m_return_adi <- c(m_return_adi, m_return_adi[4]*return_rate_adi[4]+m_return_adi[4])
m_return_adi <- c(m_return_adi, m_return_adi[5]*return_rate_adi[5]+m_return_adi[5])

m_return_ua <- c(x, x*return_rate_ua[1]+x, (x*return_rate_ua[1]+x)*return_rate_ua[2]+(x*return_rate_ua[1]+x))
m_return_ua <- c(m_return_ua, m_return_ua[3]*return_rate_ua[3]+m_return_ua[3])
m_return_ua <- c(m_return_ua, m_return_ua[4]*return_rate_ua[4]+m_return_ua[4])
m_return_ua <- c(m_return_ua, m_return_ua[5]*return_rate_ua[5]+m_return_ua[5])

Year <- year(c(start_date,year1,year2,year3,year4,lastdate))

return_df <- bind_cols(Year, m_return_NKE, m_return_SP500, m_return_adi, m_return_ua)

return_df <- return_df %>% 
    rename(
      Year = ...1,
      Nike = ...2,
      SP500 = ...3,
      Adidas = ...4,
      UA = ...5
    )

mel_return_df <- reshape2::melt(return_df, id.var = "Year")
mel_return_df$value <- round(mel_return_df$value)

return_to_date <- return_df[return_df$Year == "2022", ]
return_to_date <- return_to_date[2:5]-1000

avg_RR <- ((return_to_date[1:4]/1000*100)/5)

return_to_date <- bind_rows(return_to_date,avg_RR)

return_to_date <- t(round(return_to_date,2))

colnames(return_to_date) <- c("return in $","Yearly avg. return [%]")

tt2 <- ttheme_minimal()

print(return_plot <- mel_return_df %>%
          ggplot(aes(x = Year, y = value, color = variable)) +
          geom_line()+
          geom_point()+
          theme_classic()+
        theme(legend.position="top",
        legend.title=element_blank())+
          labs(x = 'Year',
           y = "Return in USD",
           title = "Return on investment of 1000$")+
  annotation_custom(tableGrob(return_to_date, theme = tt2), xmin=2018, xmax=2018.3, ymin=2000, ymax=3500)
)

```

```{r, Forecast}

ticker <- "NKE"

# counts 5 years into the past and sets it as start date for the plots
  
start_date <- ymd(format(Sys.Date())) - years(5)

prices <- tq_get(ticker,
                 from = start_date,
                 to = format(Sys.Date()),
                 get = "stock.prices")

prices <- prices %>% 
    rename(
      ticker = symbol,
    )

mean_NKE_price <- round(mean(prices$adjusted),2)
mean_NKE_price <- data.frame(mean_NKE_price)

ticker_plot <- prices %>%
          ggplot(aes(x = date, y = adjusted, color = ticker)) +
          geom_line()+
          geom_hline(data = mean_NKE_price, aes(yintercept = mean_NKE_price, color = ticker))+
          
          theme_classic()+
        labs(x = 'Year',
           y = "Stock Price in USD",
           title = "Nike Stock Price past 5 Years")+
        geom_text(data = mean_NKE_price, aes(x = prices$date[250], y = mean_NKE_price, label = paste("avg.", mean_NKE_price, Stock$list$Currency), vjust = -0.3), show.legend = F
                  )

Stock_info <- bind_cols(Stock$list[3],Stock$list[5],Stock$list[6],PPS_data$`2022`[6], PPS_data$`2022`[8]*100)
rownames(Stock_info) <- ""

Stock_info <- Stock_info %>% 
    rename(
      "Price [$]" = Price,
      "ISP [$]" = ...4,
      "Discount [%]" = ...5,
    )

t <- ticker_plot +
  annotation_custom(tableGrob(Stock_info, theme = tt2), xmin=prices$date[400], xmax=prices$date[450], ymin=160, ymax=170)

```